services:
  app:
    container_name: weather-rest-api
    image: weather-rest-api:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./vars.env
    depends_on:
      - database

  database:
    container_name: postgres_database
    image: postgres:17
    env_file:
      - ./vars.env


