spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 250000
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: weather

  servlet:
    multipart:
      max-file-size: 5MB




app:
  session:
    minutes-before-expire: 120
    cookie:
      name: CUSTOM_SESSION
      max-age-hours: 200

  urls:
    without-auth-allowed: /weather/api/auth/login,
      /weather/api/auth/registration
    always-allowed: /weather/api/locations, /weather/api/weather

  weather:
    open-weather-api:
      key: ${WEATHER_KEY}
      base-url: https://api.openweathermap.org/
      geocoding:
        url: geo/1.0/direct?q=%s&limit=%s&appid=%s
        default-limit: 5
      current-weather:
        url: data/2.5/weather?lat=%s&lon=%s&appid=%s&units=metric





