spring:
  datasource:
    url: jdbc:postgresql://192.168.0.125:3434/postgres
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: weather

  mvc:
    servlet:
      path: /weather/api

session:
  expires-after: 60
  cookie:
    name: USER_SESSION
    max-age: 3600

