spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 250000
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: weather

  servlet:
    multipart:
      max-file-size: 5MB


app:
  session:
    minutes-before-expire: 120
    authorized-user-attribute-name: authorizedUser
    cookie:
      name: CUSTOM_SESSION
      max-age-hours: 200

  urls:
    without-auth-allowed: /weather/api/auth/login,
      /weather/api/auth/registration
    always-allowed: /weather/api/images

  upload:
    image:
      directory: ./resources/images
      allowed-formats: .png , .jpg , .jpeg
      base-url: /weather/api/images/

  weather:
    open-weather-api:
#      key: ${WEATHER_KEY}
      base-url: https://api.openweathermap.org/
      geocoding-url: geo/1.0/direct?q=%s&limit=%s&appid=%s
      weather-url: data/2.5/weather?lat=%s&lon=%s&appid=%s&units=metric





