spring:
  datasource:
    url: jdbc:postgresql://192.168.0.125:3434/postgres
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
      default_schema: weather
  mvc:
    servlet:
      path: /weather/api
  servlet:
    multipart:
      max-file-size: 5MB


app:
  session:
    minutes-before-expire: 120
    cookie-name: USER_SESSION

  urls:
    without-auth-allowed: /weather/api/auth/login,
      /weather/api/auth/registration
    always-allowed: /weather/api/images


  upload:
    image:
      dir: ./resources/images
      allowed-formats: .png , .jpg , .jpeg




